package models.api;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class PlanAttributes {
    private boolean
     GROUP_ENABLED;
    private String
             HYPEREXECUTE_PLAN_STARTS_AT,
            SMARTUI_PLAN_STARTS_AT,
            SUBSCRIBED_AT,
            priorityBucket;
    private long
             MAX_AUTOMATION_TESTING_CONCURRENCY,
             MAX_AUTOMATION_TESTING_MINS_LIFETIME,
             MAX_AUTOMATION_TESTING_MINS_LIFETIME_DAYS,
             MAX_AUTOMATION_TESTING_MINS_PER_MONTH,
             MAX_AUTOMATION_TESTING_QUEUE,
             MAX_HYPEREXECUTE_LINUX_OS_CONCURRENCY,
             MAX_HYPEREXECUTE_MAC_OS_CONCURRENCY,
             MAX_HYPEREXECUTE_MINS_LIFETIME_DAYS,
             MAX_HYPEREXECUTE_MINUTES,
             MAX_HYPEREXECUTE_PLATFORM_CONCURRENCY,
             MAX_HYPEREXECUTE_WINDOWS_OS_CONCURRENCY,
             MAX_MANUAL_APP_TESTING_APP_UPLOAD_LIMIT,
             MAX_MANUAL_APP_TESTING_MINS_LIFETIME,
             MAX_MANUAL_BROWSER_TESTING_CONCURRENCY,
            MAX_MANUAL_BROWSER_TEST_COUNT_PER_MONTH,
             MAX_MANUAL_BROWSER_TEST_DURATION_MINS,
             MAX_MANUAL_VIRTUAL_APP_TEST_COUNT_PER_MONTH,
             MAX_MOBILE_AUTOMATION_TESTING_CONCURRENCY,
             MAX_PLATFORM_CONCURRENCY,
             MAX_RESPONSIVE_TESTS_PER_MONTH,
             MAX_RESPONSIVE_TEST_CONCURRENCY,
             MAX_RESPONSIVE_TEST_QUEUE,
             MAX_SCREENSHOT_TESTS_PER_MONTH,
             MAX_SCREENSHOT_TEST_CONCURRENCY,
             MAX_SCREENSHOT_TEST_QUEUE,
             MAX_USERS,
             SMARTUI_SCREENSHOT_COUNT_PER_MONTH,
             orgId;
}
